# Generated by Django 4.1.7 on 2023-05-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanicimalzeme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
