# Generated by Django 4.1.7 on 2023-04-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='aciklama',
        ),
    ]
