# Generated by Django 4.1.7 on 2023-06-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_kullanicimalzeme_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanicimalzeme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
