# Generated by Django 4.1.7 on 2023-04-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='defter',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='kisilik',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='vakit',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
