# Generated by Django 4.1.7 on 2023-05-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_malzeme_malzeme_adet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malzeme',
            name='malzeme_adet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
