# Generated by Django 4.1.7 on 2023-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_malzeme_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='kalori',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='tarif',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
