# Generated by Django 4.1.7 on 2023-05-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_kalori_movie_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmalzeme',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
